apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
        - name: admiring-goldwasser
          image: dorina12345/image-simple-app:latest
          ports:
            - containerPort: 80
